/*
 * File: app/store/profileStore.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WideScreenCalc.store.profileStore', {
    extend: 'Ext.data.Store',

    requires: [
        'WideScreenCalc.model.ProfileData'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'WideScreenCalc.model.ProfileData',
            storeId: 'profileStore',
            proxy: {
                type: 'ajax',
                url: 'getWSCProfile.php?format=json',
                reader: {
                    type: 'json',
                    root: 'profiles',
                    record: 'pro'
                }
            }
        }, cfg)]);
    }
});