/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WideScreenCalc.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'WideScreenCalc.controller.WSC'
    ],

    layout: {
        align: 'center',
        pack: 'center',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    width: 650,
                    title: 'Wide Screen Calculator',
                    items: [
                        {
                            xtype: 'form',
                            bodyPadding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'lblShowTitle',
                                    fieldLabel: 'Show Title',
                                    blankText: 'Enter a Show Title'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'lblShowLocation',
                                    fieldLabel: 'Show Location'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    itemId: 'cmbProfile',
                                    fieldLabel: 'Load Profile',
                                    displayField: 'ProfileName',
                                    store: 'profileStore',
                                    listeners: {
                                        select: {
                                            fn: me.onCmbProfileSelect,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnSave',
                                    text: 'Save Profile',
                                    listeners: {
                                        click: {
                                            fn: me.onBtnSaveClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            items: [
                                {
                                    xtype: 'panel',
                                    itemId: 'screenDetails',
                                    layout: {
                                        align: 'stretch',
                                        pack: 'center',
                                        type: 'hbox'
                                    },
                                    title: 'Screens',
                                    items: [
                                        {
                                            xtype: 'form',
                                            flex: 1,
                                            bodyPadding: 10,
                                            title: 'Screen Inputs',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'hsize',
                                                    fieldLabel: 'Horizontal Size',
                                                    listeners: {
                                                        change: {
                                                            fn: me.onHsizeChange,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'vsize',
                                                    fieldLabel: 'Vertical Size'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'aspectRatio',
                                                    fieldLabel: 'Aspect Ratio',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 3
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'vhff',
                                                    fieldLabel: 'Vert. Ht From Floor'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'form',
                                            flex: 1,
                                            bodyPadding: 10,
                                            title: 'Projector Information',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'HNatPixRate',
                                                    fieldLabel: 'Horz. Native Pixel Rate'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'VNatPixRate',
                                                    fieldLabel: 'Vert. Native Pixel Rate'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'projAspectRatio',
                                                    fieldLabel: 'Aspect Ratio',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 3
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'numprojectors',
                                                    fieldLabel: 'Num. of Projectors'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    itemId: 'sizePerStack',
                                                    fieldLabel: 'Size Per Stack'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'pixPerInch',
                                                    fieldLabel: 'Pixels Per Inch',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 3
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'overlapSize',
                                                    fieldLabel: 'Overlap Size',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'fieldset',
                                                    title: 'Lensing',
                                                    items: [
                                                        {
                                                            xtype: 'numberfield',
                                                            anchor: '100%',
                                                            itemId: 'lens',
                                                            fieldLabel: 'Lens',
                                                            submitLocaleSeparator: false
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            anchor: '100%',
                                                            itemId: 'distance',
                                                            fieldLabel: 'Distance'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'form',
                                            flex: 1,
                                            bodyPadding: 10,
                                            title: 'Spyder Pixel Information',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'spyHNatPixRate',
                                                    fieldLabel: 'Horz. Native Pixel Rate',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'spyVNatPixRate',
                                                    fieldLabel: 'Vert. Native Pixel Rate',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'spyAspectRatio',
                                                    fieldLabel: 'Aspect Ratio',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 3
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'spyOverlap',
                                                    fieldLabel: 'Overlap',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'spyScreenTotalPix',
                                                    fieldLabel: 'Screen Total Pixels',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'spyOpMonH',
                                                    fieldLabel: 'OpMon Format H',
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'spyOpMonV',
                                                    fieldLabel: 'OpMon Format V',
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'spyOpMonTotalPix',
                                                    fieldLabel: 'OpMon Total Pix',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'spyTotalPix',
                                                    fieldLabel: 'Spyder Total Pix',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'button',
                                    dock: 'bottom',
                                    width: 50,
                                    text: 'Show Layout',
                                    tooltip: 'Show layout of screens',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                afterlayout: {
                    fn: me.onViewportAfterLayout,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onCmbProfileSelect: function(combo, records, eOpts) {
        var record = records[0].data;
        hsize.setValue(record.HSize);
        vsize.setValue(record.VSize);
        vhff.setValue(record.VHFF);
        HNatPixRate.setValue(record.HNPR);
        VNatPixRate.setValue(record.VNPR);
        numprojectors.setValue(record.NumProjector);
        spyOpMonH.setValue(record.HOpMon);
        spyOpMonV.setValue(record.VOpMon);
    },

    onBtnSaveClick: function(button, e, eOpts) {

    },

    onHsizeChange: function(field, newValue, oldValue, eOpts) {

    },

    onButtonClick: function(button, e, eOpts) {
        var items = [];
        var fxr = 10;
        // Left screens measurements
        items.push(wsCalc.drawScreens(20, 10, fxr, "left"));
        // Center measurements
        items.push(wsCalc.drawScreens(20, (wsCalc.vsize * fxr) + 100, fxr, "center"));

        var drawComponent = Ext.create('Ext.draw.Component', {
            viewBox: false,
            items: items,
            padding: 20,
            layout: 'stretch',
            align: 'middle',
            width: (wsCalc.hsize * fxr) + 300,
            height: ((wsCalc.vsize * fxr)* 2) + 300
        });


        Ext.create('Ext.Window', {
            width: (wsCalc.hsize * fxr) + 100,
            height: ((wsCalc.vsize * fxr)* 2) + 300,
            layout: 'hbox',
            align: 'middle',
            autoScroll: true,
            items: [drawComponent]
        }).show();


    },

    onViewportAfterLayout: function(container, layout, eOpts) {
        wsCalc = WideScreenCalc.controller.WSC;
        // Events
        var btnSave = this.down('#btnSave');
        btnSave.on('click', this.onClick, this);

        hsize = this.down('#hsize');
        hsize.on('change', this.onChange, this);

        vsize = this.down('#vsize');
        vsize.on('change', this.onChange, this);

        vhff = this.down('#vhff');
        vhff.on('change', this.onChange, this);

        aspectRatio = this.down('#aspectRatio');

        HNatPixRate = this.down('#HNatPixRate');
        HNatPixRate.on('change', this.onChange, this);

        VNatPixRate = this.down('#VNatPixRate');
        VNatPixRate.on('change', this.onChange, this);

        projAspectRatio = this.down('#projAspectRatio');

        numprojectors = this.down('#numprojectors');
        numprojectors.on('change', this.onChange, this);

        sizePerStack = this.down('#sizePerStack');

        pixPerInch = this.down('#pixPerInch');

        overlapSize = this.down('#overlapSize');

        lens = this.down('#lens');
        lens.on('change', this.onChange, this);

        distance = this.down('#distance');
        distance.on('change', this.onChange, this);


        spyHNatPixRate = this.down('#spyHNatPixRate');
        spyVNatPixRate = this.down('#spyVNatPixRate');

        spyOpMonH = this.down('#spyOpMonH');
        spyOpMonH.on('change', this.OnspyOpMonTotalPixChange, this);

        spyOpMonV = this.down('#spyOpMonV');
        spyOpMonV.on('change', this.OnspyOpMonTotalPixChange, this);

        spyOpMonTotalPix = this.down('#spyOpMonTotalPix');

        spyTotalPix = this.down('#spyTotalPix');
        spyAspectRatio = this.down('#spyAspectRatio');
        spyScreenTotalPix = this.down('#spyScreenTotalPix');
        spyOverlap = this.down('#spyOverlap');
    },

    onChange: function(el) {

        wsCalc.hsize = hsize.value;
        wsCalc.vsize = vsize.value;
        wsCalc.vhff = vhff.value;
        var asprat = wsCalc.getAspectRatio();
        aspectRatio.setValue(wsCalc.getAspectRatio());

        // Projector Info calcs
        wsCalc.HNatPixRate = HNatPixRate.value;
        wsCalc.VNatPixRate = VNatPixRate.value;
        var num = projAspectRatio.setValue(wsCalc.getProjAspectRatio());
        wsCalc.numprojectors = numprojectors.value;

        // spyder pixel info
        pixPerInch.setValue(wsCalc.getPixPerInch());

        // StackSize
        sizePerStack.setValue(wsCalc.getStackWidth() + ' Wide by ' + wsCalc.vsize + ' high');
        // lens & dist
        if (el.itemId == 'distance') {
            wsCalc.distance = distance.value;
            num = wsCalc.distance / wsCalc.getStackWidth();
            roundnum = Math.round(num * Math.pow(10, 2)) / Math.pow(10, 2);
            wsCalc.lens = roundnum;
            // change dist
            lens.setRawValue(wsCalc.lens);
        } else {
            wsCalc.lens = lens.value;
            num = wsCalc.lens * wsCalc.getStackWidth();
            roundnum = Math.round(num * Math.pow(10, 2)) / Math.pow(10, 2);
            wsCalc.distance = roundnum;
            distance.setRawValue(wsCalc.distance);
        }

        spyHNatPixRate.setValue(wsCalc.getSpyHNatPixRate());
        spyVNatPixRate.setValue(wsCalc.getSpyVNatPixRate());
        spyAspectRatio.setValue(wsCalc.getSpyAspectRatio());

        try
        {
            // Screen overlap size
            overlapSize.setValue(Ext.Number.toFixed(wsCalc.getOverlapSize(), 0));
            // Spyder Overlap
            Ext.Number.toFixed(spyOverlap.setValue(wsCalc.getSpyOverlap()), 0);
        }
        catch(err){}

    },

    OnspyOpMonTotalPixChange: function(el) {

        wsCalc.spyOpMonV = spyOpMonV.value;
        wsCalc.spyOpMonH = spyOpMonH.value;
        spyOpMonTotalPix.setValue(wsCalc.getSpyOpMonTotalPix());
        spyTotalPix.setValue(wsCalc.getSpyTotalPix());
        spyScreenTotalPix.setValue(wsCalc.getSpyScreenTotalPix());
    }

});