/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WideScreenCalc.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'WideScreenCalc.controller.WSC'
    ],

    layout: {
        align: 'center',
        pack: 'center',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    width: 650,
                    title: 'Wide Screen Calculator',
                    items: [
                        {
                            xtype: 'form',
                            itemId: 'profileForm',
                            bodyPadding: 10,
                            title: '',
                            url: 'deleteProfile.php',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'lblShowTitle',
                                    fieldLabel: 'Show Title',
                                    submitValue: false,
                                    blankText: 'Enter a Show Title'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'lblShowLocation',
                                    fieldLabel: 'Show Location',
                                    submitValue: false
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    itemId: 'cmbProfile',
                                    fieldLabel: 'Load Profile',
                                    name: 'profileID',
                                    displayField: 'ProfileName',
                                    store: 'profileStore',
                                    valueField: 'ID',
                                    listeners: {
                                        select: {
                                            fn: me.onCmbProfileSelect,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnDelete',
                                    text: 'Delete Selected Profile',
                                    listeners: {
                                        click: {
                                            fn: me.onBtnDeleteClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            itemId: 'screenForm',
                            url: 'updateProfile.php',
                            items: [
                                {
                                    xtype: 'panel',
                                    itemId: 'screenDetails',
                                    layout: {
                                        align: 'stretch',
                                        pack: 'center',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            defaults: {
                                                width: 200
                                            },
                                            bodyPadding: 10,
                                            title: 'Screen Inputs',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'hsize',
                                                    fieldLabel: 'Horizontal Size',
                                                    name: 'hsize'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'vsize',
                                                    fieldLabel: 'Vertical Size',
                                                    name: 'vsize'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'aspectRatio',
                                                    fieldLabel: 'Aspect Ratio',
                                                    name: 'aspectRatio',
                                                    submitValue: false,
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 3
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'vhff',
                                                    fieldLabel: 'Vert. Ht From Floor',
                                                    name: 'vhff'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'saveBtn',
                                                    text: 'Save Profile',
                                                    tooltip: 'Save the current settings into a profile',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick1,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'hiddenfield',
                                                    fieldLabel: 'Label',
                                                    name: 'profileName'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            defaults: {
                                                width: 200
                                            },
                                            bodyPadding: 10,
                                            title: 'Projector Information',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'HNatPixRate',
                                                    fieldLabel: 'Horz. Native Pixel Rate',
                                                    name: 'HNatPixRate'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'VNatPixRate',
                                                    fieldLabel: 'Vert. Native Pixel Rate',
                                                    name: 'VNatPixRate'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'projAspectRatio',
                                                    fieldLabel: 'Aspect Ratio',
                                                    name: 'projAspectRatio',
                                                    submitValue: false,
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 3
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'numprojectors',
                                                    fieldLabel: 'Num. of Projectors',
                                                    name: 'numprojectors',
                                                    value: 1,
                                                    minValue: 1
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'sizePerStack',
                                                    fieldLabel: 'Size Per Stack',
                                                    name: 'sizePerStack',
                                                    submitValue: false
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'pixPerInch',
                                                    fieldLabel: 'Pixels Per Inch',
                                                    name: 'pixPerInch',
                                                    submitValue: false,
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 3
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'overlapSize',
                                                    fieldLabel: 'Overlap Size',
                                                    name: 'overlapSize',
                                                    submitValue: false,
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'fieldset',
                                                    title: 'Lensing',
                                                    items: [
                                                        {
                                                            xtype: 'numberfield',
                                                            anchor: '100%',
                                                            itemId: 'lens',
                                                            fieldLabel: 'Lens',
                                                            name: 'lens',
                                                            submitLocaleSeparator: false
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            anchor: '100%',
                                                            itemId: 'distance',
                                                            fieldLabel: 'Distance',
                                                            name: 'distance'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            defaults: {
                                                width: 200
                                            },
                                            bodyPadding: 10,
                                            title: 'Spyder Pixel Information',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'spyHNatPixRate',
                                                    fieldLabel: 'Horz. Native Pixel Rate',
                                                    name: 'spyHNatPixRate',
                                                    submitValue: false,
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'spyVNatPixRate',
                                                    fieldLabel: 'Vert. Native Pixel Rate',
                                                    name: 'spyVNatPixRate',
                                                    submitValue: false,
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'spyAspectRatio',
                                                    fieldLabel: 'Aspect Ratio',
                                                    name: 'spyAspectRatio',
                                                    submitValue: false,
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 3
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'spyOverlap',
                                                    fieldLabel: 'Overlap',
                                                    name: 'spyOverlap',
                                                    submitValue: false,
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'spyScreenTotalPix',
                                                    fieldLabel: 'Screen Total Pixels',
                                                    name: 'spyScreenTotalPix',
                                                    submitValue: false,
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'spyOpMonH',
                                                    fieldLabel: 'OpMon Format H',
                                                    name: 'spyOpMonH',
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'spyOpMonV',
                                                    width: 200,
                                                    fieldLabel: 'OpMon Format V',
                                                    name: 'spyOpMonV',
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'spyOpMonTotalPix',
                                                    width: 200,
                                                    fieldLabel: 'OpMon Total Pix',
                                                    name: 'spyOpMonTotalPix',
                                                    submitValue: false,
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'spyTotalPix',
                                                    width: 200,
                                                    fieldLabel: 'Spyder Total Pix',
                                                    name: 'spyTotalPix',
                                                    submitValue: false,
                                                    editable: false,
                                                    hideTrigger: true,
                                                    decimalPrecision: 0
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'button',
                                    dock: 'bottom',
                                    width: 50,
                                    menuAlign: 'tl',
                                    text: 'Show Layout',
                                    tooltip: 'Show layout of screens',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                afterlayout: {
                    fn: me.onViewportAfterLayout,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onCmbProfileSelect: function(combo, records, eOpts) {
        var record = records[0].data;
        hsize.setValue(record.HSize);
        vsize.setValue(record.VSize);
        vhff.setValue(record.VHFF);
        HNatPixRate.setValue(record.HNPR);
        VNatPixRate.setValue(record.VNPR);
        numprojectors.setValue(record.NumProjector);
        spyOpMonH.setValue(record.HOpMon);
        spyOpMonV.setValue(record.VOpMon);
    },

    onBtnDeleteClick: function(button, e, eOpts) {
        var profileName = cmbProfile.getRawValue();
        var form = this.down('#profileForm').getForm();
        if (form.isValid() && profileName !== "") {
            Ext.Msg.confirm('Delete Profile', 'Are you sure you want to delete profile ' + profileName + '?', function(btn, text){
                if (btn == 'yes'){

                    var vals = form.getValues();
                    form.submit({
                        success: function(form, action) {
                            var store = Ext.data.StoreManager.lookup('profileStore');
                            store.reload();
                            Ext.Msg.alert('Success', action.result.message);

                            cmbProfile.clearValue();
                        },
                        failure: function(form, action) {
                            Ext.Msg.alert('Failed', action.result ? action.result.message : 'No response');
                        }

                    });
                }
            });
        }
    },

    onButtonClick1: function(button, e, eOpts) {
        // The getForm() method returns the Ext.form.Basic instance:
        var form = this.down('#screenForm').getForm();
        if (form.isValid()) {
            Ext.Msg.prompt('Profile Name', 'Name these preset settings:', function(btn, text){
                if (btn == 'ok'){

                    if(text === "")
                    {
                        return;
                    }
                    // Submit the Ajax request and handle the response
                    form.setValues([{id:'profileName', value:text}]);
                    var vals = form.getValues();
                    form.submit({
                        success: function(form, action) {
                            var store = Ext.data.StoreManager.lookup('profileStore');
                            store.reload();
                            Ext.Msg.alert('Success', action.result.message);

                            cmbProfile.setValue(action.result.pkid);
                        },
                        failure: function(form, action) {
                            Ext.Msg.alert('Failed', action.result ? action.result.message : 'No response');
                        }

                    });
                }
            });
        }
    },

    onButtonClick: function(button, e, eOpts) {
        var fxr = 10;
        // Title text
        var titleItems = [];
        titleItems.push(wsCalc.drawTitle(20, 10, fxr));

        var titleComponent = Ext.create('Ext.draw.Component', {
            viewBox: false,
            items: titleItems,
            padding: 20,
            layout: 'stretch',
            align: 'middle',
            width: (wsCalc.hsize * fxr + 200),
            height: 200
        });

        // Left screens measurements
        var items = [];
        items.push(wsCalc.drawScreens(20, 10, fxr, "left"));


        var drawComponent = Ext.create('Ext.draw.Component', {
            viewBox: false,
            items: items,
            padding: 20,
            layout: 'stretch',
            align: 'middle',
            width: (wsCalc.hsize * fxr + 200),
            height: (wsCalc.vsize * fxr + 150)
        });

        // Center measurements
        var centerItems = [];
        centerItems.push(wsCalc.drawScreens(20, 10, fxr, "center"));

        var drawComponentCenter = Ext.create('Ext.draw.Component', {
            viewBox: false,
            items: centerItems,
            padding: 20,
            layout: 'stretch',
            align: 'middle',
            width: (wsCalc.hsize * fxr + 200),
            height: (wsCalc.vsize * fxr + 150)
        });

        Ext.create('Ext.Window', {
            width: (wsCalc.hsize * fxr) + 100,
            height: ((wsCalc.vsize * fxr)* 2) + 300,
            layout: 'vbox',
            align: 'middle',
            autoScroll: true,
            items: [titleComponent, drawComponent, drawComponentCenter],
            maximizable: true
        }).show();

    },

    onViewportAfterLayout: function(container, layout, eOpts) {
        wsCalc = WideScreenCalc.controller.WSC;
        cmbProfile = this.down('#cmbProfile');
        // Events

        hsize = this.down('#hsize');
        hsize.on('change', this.onChange, this);

        vsize = this.down('#vsize');
        vsize.on('change', this.onChange, this);

        vhff = this.down('#vhff');
        vhff.on('change', this.onChange, this);

        aspectRatio = this.down('#aspectRatio');

        HNatPixRate = this.down('#HNatPixRate');
        HNatPixRate.on('change', this.onChange, this);

        VNatPixRate = this.down('#VNatPixRate');
        VNatPixRate.on('change', this.onChange, this);

        projAspectRatio = this.down('#projAspectRatio');

        numprojectors = this.down('#numprojectors');
        numprojectors.on('change', this.onChange, this);

        sizePerStack = this.down('#sizePerStack');

        pixPerInch = this.down('#pixPerInch');

        overlapSize = this.down('#overlapSize');

        lens = this.down('#lens');
        lens.on('change', this.onChange, this);

        distance = this.down('#distance');
        distance.on('change', this.onChange, this);

        titleText = this.down('#lblShowTitle');
        locationText = this.down('#lblShowLocation');


        spyHNatPixRate = this.down('#spyHNatPixRate');
        spyVNatPixRate = this.down('#spyVNatPixRate');

        spyOpMonH = this.down('#spyOpMonH');
        spyOpMonH.on('change', this.OnspyOpMonTotalPixChange, this);

        spyOpMonV = this.down('#spyOpMonV');
        spyOpMonV.on('change', this.OnspyOpMonTotalPixChange, this);

        spyOpMonTotalPix = this.down('#spyOpMonTotalPix');

        spyTotalPix = this.down('#spyTotalPix');
        spyAspectRatio = this.down('#spyAspectRatio');
        spyScreenTotalPix = this.down('#spyScreenTotalPix');
        spyOverlap = this.down('#spyOverlap');
    },

    onChange: function(el) {

        wsCalc.hsize = hsize.value;
        wsCalc.vsize = vsize.value;
        wsCalc.vhff = vhff.value;
        var asprat = wsCalc.getAspectRatio();
        aspectRatio.setValue(wsCalc.getAspectRatio());

        // Projector Info calcs
        wsCalc.HNatPixRate = HNatPixRate.value;
        wsCalc.VNatPixRate = VNatPixRate.value;
        var num = projAspectRatio.setValue(wsCalc.getProjAspectRatio());
        wsCalc.numprojectors = numprojectors.value;

        // spyder pixel info
        pixPerInch.setValue(wsCalc.getPixPerInch());

        // StackSize
        sizePerStack.setValue(wsCalc.getStackWidth() + ' Wide by ' + wsCalc.vsize + ' high');
        // lens & dist
        if (el.itemId == 'distance') {
            wsCalc.distance = distance.value;
            num = wsCalc.distance / wsCalc.getStackWidth();
            roundnum = Math.round(num * Math.pow(10, 2)) / Math.pow(10, 2);
            wsCalc.lens = roundnum;
            // change dist
            lens.setRawValue(wsCalc.lens);
        } else {
            wsCalc.lens = lens.value;
            num = wsCalc.lens * wsCalc.getStackWidth();
            roundnum = Math.round(num * Math.pow(10, 2)) / Math.pow(10, 2);
            wsCalc.distance = roundnum;
            distance.setRawValue(wsCalc.distance);
        }

        spyHNatPixRate.setValue(wsCalc.getSpyHNatPixRate());
        spyVNatPixRate.setValue(wsCalc.getSpyVNatPixRate());
        spyAspectRatio.setValue(wsCalc.getSpyAspectRatio());

        try
        {
            // Screen overlap size
            overlapSize.setValue(Ext.Number.toFixed(wsCalc.getOverlapSize(), 0));
            // Spyder Overlap
            Ext.Number.toFixed(spyOverlap.setValue(wsCalc.getSpyOverlap()), 0);
        }
        catch(err){}

    },

    OnspyOpMonTotalPixChange: function(el) {

        wsCalc.spyOpMonV = spyOpMonV.value;
        wsCalc.spyOpMonH = spyOpMonH.value;
        spyOpMonTotalPix.setValue(wsCalc.getSpyOpMonTotalPix());
        spyTotalPix.setValue(wsCalc.getSpyTotalPix());
        spyScreenTotalPix.setValue(wsCalc.getSpyScreenTotalPix());
    }

});