/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WideScreenCalc.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'WideScreenCalc.controller.WSC'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    width: 650,
                    title: 'Wide Screen Calculator',
                    items: [
                        {
                            xtype: 'form',
                            bodyPadding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'lblShowTitle',
                                    fieldLabel: 'Show Title',
                                    blankText: 'Enter a Show Title'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'lblShowLocation',
                                    fieldLabel: 'Show Location'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    itemId: 'cmbProfile',
                                    fieldLabel: 'Load Profile',
                                    displayField: 'ProfileName',
                                    store: 'profileStore',
                                    listeners: {
                                        select: {
                                            fn: me.onCmbProfileSelect,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnSave',
                                    text: 'Save Profile',
                                    listeners: {
                                        click: {
                                            fn: me.onBtnSaveClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: {
                                align: 'stretch',
                                pack: 'center',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    bodyPadding: 10,
                                    title: 'Screen Inputs',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'hsize',
                                            fieldLabel: 'Horizontal Size',
                                            listeners: {
                                                change: {
                                                    fn: me.onHsizeChange,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'vsize',
                                            fieldLabel: 'Vertical Size'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'aspectRatio',
                                            fieldLabel: 'Aspect Ratio',
                                            editable: false,
                                            hideTrigger: true,
                                            decimalPrecision: 3
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'vhff',
                                            fieldLabel: 'Vert. Ht From Floor'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    bodyPadding: 10,
                                    title: 'Projector Information',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'HNatPixRate',
                                            fieldLabel: 'Horz. Native Pixel Rate'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'VNatPixRate',
                                            fieldLabel: 'Vert. Native Pixel Rate'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'projAspectRatio',
                                            fieldLabel: 'Aspect Ratio',
                                            editable: false,
                                            hideTrigger: true,
                                            decimalPrecision: 3
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'numprojectors',
                                            fieldLabel: 'Num. of Projectors'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            itemId: 'sizePerStack',
                                            fieldLabel: 'Size Per Stack'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'pixPerInch',
                                            fieldLabel: 'Pixels Per Inch',
                                            editable: false,
                                            hideTrigger: true,
                                            decimalPrecision: 3
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'overlapSize',
                                            fieldLabel: 'Overlap Size',
                                            editable: false,
                                            hideTrigger: true,
                                            decimalPrecision: 0
                                        },
                                        {
                                            xtype: 'fieldset',
                                            title: 'Lensing',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'lens',
                                                    fieldLabel: 'Lens'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    itemId: 'distance',
                                                    fieldLabel: 'Distance'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    bodyPadding: 10,
                                    title: 'Spyder Pixel Information',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'spyHNatPixRate',
                                            fieldLabel: 'Horz. Native Pixel Rate',
                                            editable: false,
                                            hideTrigger: true,
                                            decimalPrecision: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'spyVNatPixRate',
                                            fieldLabel: 'Vert. Native Pixel Rate',
                                            editable: false,
                                            hideTrigger: true,
                                            decimalPrecision: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'spyAspectRatio',
                                            fieldLabel: 'Aspect Ratio',
                                            editable: false,
                                            hideTrigger: true,
                                            decimalPrecision: 3
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'spyOverlap',
                                            fieldLabel: 'Overlap',
                                            editable: false,
                                            hideTrigger: true,
                                            decimalPrecision: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'spyScreenTotalPix',
                                            fieldLabel: 'Screen Total Pixels',
                                            editable: false,
                                            hideTrigger: true,
                                            decimalPrecision: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'spyOpMonH',
                                            fieldLabel: 'OpMon Format H',
                                            decimalPrecision: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'spyOpMonV',
                                            fieldLabel: 'OpMon Format V',
                                            decimalPrecision: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'spyOpMonTotalPix',
                                            fieldLabel: 'OpMon Total Pix',
                                            editable: false,
                                            hideTrigger: true,
                                            decimalPrecision: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'spyTotalPix',
                                            fieldLabel: 'Spyder Total Pix',
                                            editable: false,
                                            hideTrigger: true,
                                            decimalPrecision: 0
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                afterlayout: {
                    fn: me.onViewportAfterLayout,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onCmbProfileSelect: function(combo, records, options) {
        var record = records[0].data;
        hsize.setValue(record.HSize);
        vsize.setValue(record.VSize);
        vhff.setValue(record.VHFF);
        HNatPixRate.setValue(record.HNPR);
        VNatPixRate.setValue(record.VNPR);
        numprojectors.setValue(record.NumProjector);
        spyOpMonH.setValue(record.HOpMon);
        spyOpMonV.setValue(record.VOpMon);
    },

    onBtnSaveClick: function(button, e, options) {
        // Screens
        var screens = wsCalc.getScreens();
        // Spyder Overlap
        //alert(screens[0].leftLeft + '; ' + screens[0].leftCenter + '; ' + screens[0].leftRight + '; ' + screens[0].centerCenter);
        var fxr = 10; var offset = 20;
        var items = [];
        var textItems = [];
        var screenWidth = wsCalc.getScreenWidth();
        var screenHeight = wsCalc.vsize;
        var yMainOffset = 10;
        for(var i = 0; i<screens.length; i++)
        {
            // Display logo as background
            var logo = {
                type: "image",
                src: "resources/vx3logo.png",
                height: screenHeight * fxr,
                width: screenWidth * fxr,
                x: (screens[i].leftLeft * fxr) + offset,
                y: yMainOffset
            };
            items.push(logo);

            // Draw the screens
            var item = {
                type: 'rect',
                fill: '#ffc',
                height: screenHeight * fxr,
                width: screenWidth * fxr,
                x: (screens[i].leftLeft * fxr) + offset,
                y: yMainOffset,
                opacity: 0.5,
                stroke: 'red',
                'stroke-width': 2,
                listeners: {
                    mouseover: mouseMove,
                    mouseout: mouseOut
                }       
            };
            // Odd numbers offset by 55, even by 30 to stagger text
            var yOffset = 85;
            if(i%2 === 0)
            yOffset = 45;
            var xOffset = -20;
            items.push(item);
            // Left Decimal Dimension text
            var textItem = {
                type: "text",
                text: screens[i].leftLeft + '"',
                x: (screens[i].leftLeft * fxr) + xOffset + offset,
                y: (screenHeight * fxr) + yOffset,
                fill: "green",
                font: "10px Arial",
                rotate: {
                    degrees: 270
                }
            };
            items.push(textItem);
            // Feet + inches
            var feetInches = wsCalc.convertFeet(screens[i].leftLeft);
            var feetTextItem = Ext.clone(textItem);
            feetTextItem.text = feetInches;
            feetTextItem.x = feetTextItem.x + 18;
            items.push(feetTextItem);

            // Center dimension
            textItem = {
                type: "text",
                text: screens[i].leftCenter,
                x: (screens[i].leftCenter * fxr) + xOffset + offset,
                y: (screenHeight * fxr) + yOffset,
                fill: "green",
                font: "10px Arial",
                rotate: {
                    degrees: 270
                }
            };
            items.push(textItem);
            // Feet + inches
            feetInches = wsCalc.convertFeet(screens[i].leftCenter);
            feetTextItem = Ext.clone(textItem);
            feetTextItem.text = feetInches;
            feetTextItem.x = feetTextItem.x + 18;
            items.push(feetTextItem);

            // Right dimension
            textItem = {
                type: "text",
                text: screens[i].leftRight,
                x: (screens[i].leftRight * fxr) + xOffset + offset,
                y: (screenHeight * fxr) + yOffset,
                fill: "green",
                font: "10px Arial",
                rotate: {
                    degrees: 270
                }
            };
            items.push(textItem);
            // Feet + inches
            feetInches = wsCalc.convertFeet(screens[i].leftRight);
            feetTextItem = Ext.clone(textItem);
            feetTextItem.text = feetInches;
            feetTextItem.x = feetTextItem.x + 18;
            items.push(feetTextItem);


            // Left Dimension lines
            var x1 = (screens[i].leftLeft * fxr) + offset;
            var y1 = (screenHeight * fxr) + yMainOffset ;
            var lineItem = {
                type: "path",
                path: "M" + x1 + " " + y1 + "v " + yOffset,
                stroke: "purple"
            };

            items.push(lineItem);

            // Center Dimension lines
            x1 = (screens[i].leftCenter * fxr) + offset;
            y1 = (screenHeight * fxr) + yMainOffset ;
            lineItem = {
                type: "path",
                path: "M" + x1 + " " + y1 + "v " + yOffset,
                stroke: "purple"
            };

            items.push(lineItem);

            // Right Dimension lines
            x1 = (screens[i].leftRight * fxr) + offset;
            y1 = (screenHeight * fxr) + yMainOffset ;
            lineItem = {
                type: "path",
                path: "M" + x1 + " " + y1 + "v " + yOffset,
                stroke: "purple"
            };

            items.push(lineItem);
        }

        var drawComponent = Ext.create('Ext.draw.Component', {
            viewBox: false,
            items: items,
            padding: 20,
            layout: 'stretch',
            align: 'middle',
            width: (wsCalc.hsize * fxr) + 300,
            height: ((wsCalc.vsize * fxr)* 2) + 300
        });


        Ext.create('Ext.Window', {
            width: (wsCalc.hsize * fxr) + 100,
            height: ((wsCalc.vsize * fxr)* 2) + 300,
            layout: 'hbox',
            align: 'middle',
            items: [drawComponent]
        }).show();

        function mouseMove(el, t, eOpts) {
            el.setAttributes({stroke: 'blue', "stroke-width": 3}, true);
        }

        function mouseOut(el, t, eOpts) {
            el.setAttributes({stroke: 'red', "stroke-width": 2}, true);
        }
    },

    onHsizeChange: function(field, newValue, oldValue, options) {

    },

    onViewportAfterLayout: function(abstractcontainer, layout, options) {
        wsCalc = WideScreenCalc.controller.WSC;
        // Events
        var btnSave = this.down('#btnSave');
        btnSave.on('click', this.onClick, this);

        hsize = this.down('#hsize');
        hsize.on('change', this.onChange, this);

        vsize = this.down('#vsize');
        vsize.on('change', this.onChange, this);

        vhff = this.down('#vhff');
        vhff.on('change', this.onChange, this);

        aspectRatio = this.down('#aspectRatio');

        HNatPixRate = this.down('#HNatPixRate');
        HNatPixRate.on('change', this.onChange, this);

        VNatPixRate = this.down('#VNatPixRate');
        VNatPixRate.on('change', this.onChange, this);

        projAspectRatio = this.down('#projAspectRatio');

        numprojectors = this.down('#numprojectors');
        numprojectors.on('change', this.onChange, this);

        sizePerStack = this.down('#sizePerStack');

        pixPerInch = this.down('#pixPerInch');

        overlapSize = this.down('#overlapSize');

        lens = this.down('#lens');
        lens.on('change', this.onChange, this);

        distance = this.down('#distance');
        distance.on('change', this.onChange, this);


        spyHNatPixRate = this.down('#spyHNatPixRate');
        spyVNatPixRate = this.down('#spyVNatPixRate');

        spyOpMonH = this.down('#spyOpMonH');
        spyOpMonH.on('change', this.OnspyOpMonTotalPixChange, this);

        spyOpMonV = this.down('#spyOpMonV');
        spyOpMonV.on('change', this.OnspyOpMonTotalPixChange, this);

        spyOpMonTotalPix = this.down('#spyOpMonTotalPix');

        spyTotalPix = this.down('#spyTotalPix');
        spyAspectRatio = this.down('#spyAspectRatio');
        spyScreenTotalPix = this.down('#spyScreenTotalPix');
        spyOverlap = this.down('#spyOverlap');
    },

    onChange: function(el) {

        wsCalc.hsize = hsize.value;
        wsCalc.vsize = vsize.value;
        wsCalc.vhff = vhff.value;
        var asprat = wsCalc.getAspectRatio();
        aspectRatio.setValue(wsCalc.getAspectRatio());

        // Projector Info calcs
        wsCalc.HNatPixRate = HNatPixRate.value;
        wsCalc.VNatPixRate = VNatPixRate.value;
        var num = projAspectRatio.setValue(wsCalc.getProjAspectRatio());
        wsCalc.numprojectors = numprojectors.value;

        // spyder pixel info
        pixPerInch.setValue(wsCalc.getPixPerInch());

        // StackSize
        sizePerStack.setValue(wsCalc.getStackWidth() + ' Wide by ' + wsCalc.vsize + ' high');
        // lens & dist
        if (el.itemId == 'distance') {
            wsCalc.distance = distance.value;
            num = wsCalc.distance / wsCalc.getStackWidth();
            roundnum = Math.round(num * Math.pow(10, 2)) / Math.pow(10, 2);
            wsCalc.lens = roundnum;
            // change dist
            lens.setRawValue(wsCalc.lens);
        } else {
            wsCalc.lens = lens.value;
            num = wsCalc.lens * wsCalc.getStackWidth();
            roundnum = Math.round(num * Math.pow(10, 2)) / Math.pow(10, 2);
            wsCalc.distance = roundnum;
            distance.setRawValue(wsCalc.distance);
        }

        spyHNatPixRate.setValue(wsCalc.getSpyHNatPixRate());
        spyVNatPixRate.setValue(wsCalc.getSpyVNatPixRate());
        spyAspectRatio.setValue(wsCalc.getSpyAspectRatio());

        try
        {
            // Screen overlap size
            overlapSize.setValue(Ext.Number.toFixed(wsCalc.getOverlapSize(), 0));
            // Spyder Overlap
            Ext.Number.toFixed(spyOverlap.setValue(wsCalc.getSpyOverlap()), 0);
        }
        catch(err){}

    },

    OnspyOpMonTotalPixChange: function(el) {

        wsCalc.spyOpMonV = spyOpMonV.value;
        wsCalc.spyOpMonH = spyOpMonH.value;
        spyOpMonTotalPix.setValue(wsCalc.getSpyOpMonTotalPix());
        spyTotalPix.setValue(wsCalc.getSpyTotalPix());
        spyScreenTotalPix.setValue(wsCalc.getSpyScreenTotalPix());
    }

});