/*
 * File: app/view/baseForm.js
 * Date: Thu Nov 10 2011 15:23:43 GMT-0500 (Eastern Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
var wsCalc;
var hsize, vsize, vhff;
var HNatPixRate, VNatPixRate, projAspectRatio, numprojectors;
var aspectRatio, sizePerStack, pixPerInch, overlapSize, lens, distance;
var spyHNatPixRate, spyVNatPixRate, spyAspectRatio, spyOverlap, spyScreenTotalPix;
var spyOpMonH, spyOpMonV, spyOpMonTotalPix, spyTotalPix;
var loadProfile, titleText, locationText;


