/*
 * File: app/controller/Screen.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Screen', {
    extend: 'Ext.Base',
    alias: 'controller.Screen',

    LeftLeft: 0,
    LeftCenter: 0,
    LeftRight: 0,
    CenterLeft: 0,
    CenterCenter: 0,
    CenterRight: 0,
    StartPixelOutput: 0,
    EndPixelOutput: 0,
    StartPixelOverlap: 0,
    EndPixelOverlap: 0
});